# Generated by Django 3.2.9 on 2021-11-19 22:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=30)),
                ('descricao', models.TextField()),
                ('data_pub', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['titulo'],
            },
        ),
    ]
